apiVersion: apps/v1
kind: Deployment
metadata:
  name: tastytap-users
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tastytap-users
  template:
    metadata:
      labels:
        app: tastytap-users
    spec:
      containers:
        - name: app
          image: 264927492157.dkr.ecr.us-east-1.amazonaws.com/tastytap-users:latest
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: app-secrets
          resources:
            requests:
              cpu: 100m
              memory: 500Mi
            limits:
              cpu: 500m
              memory: 500Mi